version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /adapters/http1/go-nethttp
    schedule:
      interval: weekly
